### PR TITLE
Test docs PR preview on readthedocs

### PR DESCRIPTION
**Pull request by Mariatta**
Closes #

### CODE REVIEW

**Comment by Mariatta** [comment]
I can't seem to get the readthedocs deploy preview to work 😥 
I have tried removing and adding the webhook back.

**Comment by brettcannon** [comment]
Read the Docs throws an error for me when I try to resync the webhook.

**Comment by brettcannon** [comment]
Fixed! https://github.com/organizations/gidgethub/settings/oauth_application_policy was set to require apps to request org access. I couldn't figure out how to get Read the Docs to do that, so I switched it so any app we approve automatically gets approval.

**Comment by Mariatta** [comment]
Thanks for the help!

**Pull request closed without merging**
